In [2]:
import tensorflow as tf
import numpy as np

In [2]:
print(tf.__version__)

2.5.0


## TensorFlow Basic Syntax

### Constants

In [3]:
hello = tf.constant("hello ")
world = tf.constant("world")
print(hello) # b'hello' represents byte string; python3
print(type(hello))

tf.Tensor(b'hello ', shape=(), dtype=string)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [15]:
# TF1 requires a session to run tensorflow code usually.
# TF2 runs Eager Execution by default, No need for Sessions. (tf.Session() not required)
result = hello + world

In [17]:
tf.print(result)

hello world


In [18]:
a = tf.constant(10)
b = tf.constant(20)

In [20]:
print(a + b)
tf.print(a + b)

tf.Tensor(30, shape=(), dtype=int32)
30


### Matrix

In [22]:
# Fill

fill_mat = tf.fill((5,5), 3)
fill_mat

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]], dtype=int32)>

In [27]:
# Zeros

zero_mat = tf.zeros((3,3), dtype=np.int32)
zero_mat

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [28]:
# Ones

one_mat = tf.ones((3,4))
one_mat

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [7]:
# Random

ran_mat = tf.random.normal((4,4), mean=0, stddev=2.0) # In TF1, it was tf.random_normal
ran_mat

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-0.2684068 , -0.74726945,  0.88202053,  1.6282356 ],
       [ 0.01758729, -0.35391816,  2.052887  ,  1.1894195 ],
       [-0.9966169 , -1.3076576 , -0.5862183 ,  3.146374  ],
       [-2.2406988 ,  1.2894658 , -1.6540389 ,  2.0600786 ]],
      dtype=float32)>

In [9]:
# Random Uniform
tf.random.uniform((4,4), minval=0, maxval=1)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.34985125, 0.21115744, 0.4019301 , 0.39896095],
       [0.8578422 , 0.99546957, 0.7420329 , 0.8205298 ],
       [0.23450744, 0.45629215, 0.3514229 , 0.5722505 ],
       [0.31737995, 0.6283146 , 0.8245152 , 0.3072964 ]], dtype=float32)>

### Matrix Operations

In [47]:
a = tf.ones((4,3), dtype=np.int32)
a

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [48]:
a.get_shape()

TensorShape([4, 3])

In [53]:
b = tf.constant([[10],[20],[30]], dtype=np.int32)
b.get_shape()

TensorShape([3, 1])

In [54]:
c = tf.constant([[10, 20], [30, 40], [50, 60]], dtype=np.int32)
c.get_shape()

TensorShape([3, 2])

In [55]:
# Matrix multiplication (Dot product) 
# For multiplication of 2 matrix, it is important to get the column count of first Matrix 
# should match row count of second Matrix.

tf.matmul(a, b)

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[60],
       [60],
       [60],
       [60]], dtype=int32)>

In [56]:
tf.matmul(a, c)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 90, 120],
       [ 90, 120],
       [ 90, 120],
       [ 90, 120]], dtype=int32)>

In [76]:
# To get some of all values in each row in a matrix, 
# multiply that matrix by unit matrix of size (no.of cols, 1)

t = tf.random.uniform((4, 3), dtype=np.int32, maxval=10)
print(t)
print(t.get_shape())
unt = tf.ones((t.get_shape()[1], 1), dtype=np.int32)
tf.matmul(t, unt)

tf.Tensor(
[[7 0 3]
 [9 7 3]
 [5 0 4]
 [0 2 9]], shape=(4, 3), dtype=int32)
(4, 3)


<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[10],
       [19],
       [ 9],
       [11]], dtype=int32)>

## TensorFlow Graphs

* Graphs are set of connected nodes which is called vertices.
* TF constructs the graph and executes it.

In [5]:
# n1, n2 - Constant Nodes
# n3 - Operation node

n1 = tf.constant(2)
n2 = tf.constant(6)
n3 = tf.add(n1, n2)
n4 = n1 + n2

print(n1)
print(n2)
print(n3)
print(n4)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)


In [18]:
# print(tf.get_default_graph()) for TF1
dflt = tf.compat.v1.get_default_graph()
print(dflt)

In [21]:
g1 = tf.Graph
with g1.as_default():
    print (tf.compat.v1.get_default_graph())
    

TypeError: as_default() missing 1 required positional argument: 'self'